image: ubuntu:latest

before_script:
  # General setup
  - apt-get update && apt-get install -y curl build-essential

  # Install Node.js for React Native
  - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
  - apt-get install -y nodejs

  # Install dependencies for Arduino
  - chmod +x setup-build-env.sh
  - ./setup-build-env.sh

stages:
  - build
  - deploy

compile:
  stage: build
  tags:
    - docker
  script:
    # Compile Arduino project
    - export PATH=$PATH:/root/bin
    - cd WioTerminal
    - echo "$SECRETS_H" > Secrets.h
    - arduino-cli lib list
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

    # Change to React Native project directory
    - cd ../mobile
    - npm install
    - npm run build # or the appropriate build command for your React Native project

release:
  stage: deploy
  tags:
    - upload
  script:
    # Arduino deploy
    - export PATH=$PATH:/root/bin
    - cd WioTerminal
    - echo "$SECRETS_H" > Secrets.h
    - arduino-cli lib list
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal
    - arduino-cli board list
    - arduino-cli upload -p $COM_PORT --fqbn Seeeduino:samd:seeed_wio_terminal

    # Deploy React Native app
    - cd ../mobile
    - npm run deploy # Update with your deploy command or script
  only:
    - tags
