image: node:18.0.0

stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18.0.0" # current node version
  EAS_ACCESS_TOKEN: "3Mg5Ly0KeNI9-hOuAz8IydXd2bDhilL-sK3RdWhO" #nabil's access token on expo

before_script:
  # Common setup tasks for both Arduino and React Native builds
  - apt-get update && apt-get install -y curl git build-essential
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'  # This loads nvm
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g expo-cli
  - npm install -g eas-cli

build-react-native:
  stage: build
  script:
    - cd mobile #to Navigate to mobile directory
    - npm install  # Ensure all dependencies are installed
    - eas build --platform android #build the android version
    - echo "React Native build successful!" # success message

compile-arduino:
  stage: build
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin
    - chmod +x setup-build-env.sh
    - ./setup-build-env.sh
    - cd WioTerminal
    - echo "$SECRETS_H" > Secrets.h
    - arduino-cli lib list
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal
    - echo "Arduino build successful!"
  except:
    - tags

release-arduino:
  stage: deploy
  tags:
    - upload
  script:
    - export PATH=$PATH:/root/bin
    - cd WioTerminal
    - echo "$SECRETS_H" > Secrets.h
    - arduino-cli lib list
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal
    - arduino-cli board list
    - arduino-cli upload -p $COM_PORT --fqbn Seeeduino:samd:seeed_wio_terminal
    - echo "Arduino upload successful!"
  only:
    - tags
