image: ubuntu:latest

before_script:
  # Install general dependencies
  - apt-get update && apt-get install -y curl build-essential
  # Install Node.js for React Native
  - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  # Run shell script for installing arduino-cli, Wio Terminal core, and project libraries
  - chmod +x setup-build-env.sh
  - ./setup-build-env.sh

stages:
  - build_cpp
  - build_js
  - deploy

compile_cpp:
  stage: build_cpp
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin
    - pwd
    - cd WioTerminal
    - echo "$SECRETS_H" > Secrets.h
    - arduino-cli lib list
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal
    - arduino-cli board list
  except:
    - tags

compile_js:
  stage: build_js
  script:
    - cd mobile
    - npm install
    - npm run lint
  tags:
    - docker
  except:
    - tags

release:
  stage: deploy
  tags:
    - upload
  script:
    - export PATH=$PATH:/root/bin
    - pwd
    - if [ -d "WioTerminal" ]; then
      cd WioTerminal
      echo "$SECRETS_H" > Secrets.h
      arduino-cli lib list
      arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal
      arduino-cli board list
      arduino-cli upload -p $COM_PORT --fqbn Seeeduino:samd:seeed_wio_terminal
      cd ..
      fi
    - if [ -d "mobile" ]; then
      cd mobile
      npm install
      npm run build
      fi
  only:
    - tags