image: ubuntu:latest

variables:
  NODE_VERSION: "14.17.0"

before_script:
  # Install dependencies and setup environment for both Arduino and React Native
  - chmod +x setup-build-env.sh               # change permissions to execute bash shell script
  - ./setup-build-env.sh
  - apt-get update && apt-get install -y curl git build-essential
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'  # This loads nvm
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  # npm install -g npm@latest # Commenting out to avoid compatibility issues
  - npm install -g expo-cli

stages:
  - build
  - test

compile:
  stage: build
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin             # Set the path to arduino-cli installation folder
    - cd WioTerminal                          # Change the directory to Arduino folder
    - echo "$SECRETS_H" > Secrets.h           # Import secrets from GitLab CI/CD settings
    - arduino-cli lib list                    # Check that libraries are installed
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal
    - arduino-cli board list                  # Check if device is connected

build-react-native:
  stage: build
  script:
    - cd mobile                      # Navigate to the React Native directory
    - npm install                    # Install dependencies
    - npm run android                # Build Android project
  artifacts:
    paths:
      - mobile/android/app/build/outputs/
  only:
    - master
    - merge_requests

test-react-native:
  stage: test
  script:
    - cd mobile
    - npm run test                             # Run tests defined in the React Native project